config/routes.rb
Pocketchange::Application.routes.draw do
  resources :categories do
    resources :transactions
  end
  get "transactions" => "transactions#index"
  
  get "home/index"
  
  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  validates_uniqueness_of :graph_position_number
  validates_uniqueness_of :cat_name
  has_many :transactions
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  has_many :budgets
  
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  
  belongs_to :category
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.build(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, :notice => 'Transaction was successfully created.' }
        format.json { render :json => @transaction, :status => :created }
      else
        format.html { render :action => "new" }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, :notice => 'Transaction was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cat_name %><br />
    <%= f.text_field :cat_name %>
  </div>
  <div class="field">
    <%= f.label :starting_balance %><br />
    <%= f.number_field :starting_balance %>
  </div>
  <div class="field">
    <%= f.label :current_balance %><br />
    <%= f.number_field :current_balance %>
  </div>
  <div class="field">
    <%= f.label :pocket_balance %><br />
    <%= f.number_field :pocket_balance %>
  </div>
  <div class="field">
    <%= f.label :change_balance %><br />
    <%= f.number_field :change_balance %>
  </div>
  <div class="field">
    <%= f.label :graph_position_number %><br />
    <%= f.number_field :graph_position_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<script>var paper = Raphael(0, 0, 2000, 475);
  var orderArray = [];
  var everythingRightOfBudget = paper.set();
</script>
<div id="text">
<% current_total = 0 %>
<% starting_total = 0 %>
<% change_total = 0 %>
<% @categories.each do |category| %>
  <% current_total = current_total + category.current_balance %>
  <% starting_total = starting_total + category.starting_balance %>
  <% change_total = change_total + category.change_balance %>
  <%= link_to 'Edit' , edit_category_path(category) %>
  <%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %>
  <script>
    categories.push(<%= category.to_json( :only => [ :id, :cat_name, :starting_balance, :current_balance, :pocket_balance, :pocket_x, :pocket_y ]).html_safe %>);
    drawCategory('<%= category.cat_name %>', <%= category.starting_balance %>, <%= category.current_balance %>, <%= category.pocket_balance %>, <%= category.graph_position_number %>,<%= current_total %>, <%= starting_total %>);
  </script>
<% end %>

<% @categories.each do |pocket_bubble| %>
  <script>
    if(<%= pocket_bubble.pocket_balance %> > 0){drawPocketBubble('<%= pocket_bubble.cat_name %>', <%= pocket_bubble.pocket_balance %>, <%= pocket_bubble.graph_position_number %>, <%= pocket_bubble.pocket_x %>, <%= pocket_bubble.pocket_y %>, <%= change_total %>);}
  </script>
<% end %>
<p><%= current_total %> of <%= starting_total %></p>

<script>
  divider.show();
  divider.glow({width: 25, opacity: .1});
  everythingRightOfBudget.push(divider);
  
  startingTotalBar.show();
  startingTotalBar.glow({width: 2, opacity: .1});
  currentTotalBar.show();
  
  //Budget Title
  var budgetTitleRect = paper.rect(divider.attr("x")/2 - 83, 0, 166, 58, 0).attr({fill: "#003300", opacity: .1, stroke: "#003300"});
  budgetTitleRect.glow({width: 4, opacity: .08});
  
  var budgetTitleText = paper.text(divider.attr("x")/2, 30, "Budget").attr("font-size", "45");
  budgetTitleText.attr("font-family", "Arial");
  budgetTitleText.attr("fill", "#006633");
  
  //Pocket Background and title
  var pocketBackground = paper.image("assets/graph2.jpg", divider.attr("x"), 0, 400, 500).attr({opacity: 1});
  pocketBackground.toBack();
  everythingRightOfBudget.push(pocketBackground);
  
  var pocketTitleRect = paper.rect(divider.attr("x") + 117, 0, 166, 58).attr({fill: "#fff", stroke: "#ccc"});
  pocketTitleRect.glow({width: 20, opacity: .1});
  
  var pocketTitleText = paper.text(divider.attr("x") + 200, 30, "Pocket").attr("font-size", "45");
  pocketTitleText.attr("font-family", "Courier New");
  pocketTitleText.attr("font-color", "#333");
  
  //Change background and title
  var changeBackground = paper.image("assets/Rock_Texture_condensed.png", divider.attr("x") + 800, 0, 667, 500);
  
  var changeBorderBox = paper.rect(divider.attr("x") + 810, 10, 667, 455, 5).attr({stroke: "#ccc", opacity: .95});
  changeBorderBox.attr("stroke-width", 20);
  changeBorderBox.glow({width: 20, opacity: .8});
  
  //var changeDisplayBubble = paper.circle(divider.attr("x") + 800 + 667/2, 475/2, 130).attr({fill: "#fff", stroke: "#669933", opacity: .8});
  //changeDisplayBubble.glow({width: 5, opacity: .3});
  
  var changeTitleRect = paper.rect(divider.attr("x") + 795, 80, 58, 140, 5).attr({fill: "#fff", stroke: "#fff", opacity: .9});
  changeTitleRect.glow({width: 20, opacity: .6});
  
  var changeTitleText = paper.text(divider.attr("x") + 820, 150, "Change!").attr("font-size", "28");
  changeTitleText.rotate(270, divider.attr("x") + 820, 150);
  
  var changeLittleBox = paper.rect(divider.attr("x") + 800 + 667/2 - 75, 475/2 - 50, 150, 75, 20).attr({fill: "#cc9900", stroke: "#333", opacity: .7});
  changeLittleBox.glow({width: 10, opacity: .7});
  
  //This shows the current change balance
  drawChange(<%= change_total %>);
  
  //Transactions background and title
  var transactionsBackground = paper.image("assets/chalkboard_s.png", divider.attr("x") + 400, 0, 400, 500);
  transactionsBackground.glow({width: 10, opacity: .5});
  everythingRightOfBudget.push(transactionsBackground);
  
  var transTitleRect = paper.rect(divider.attr("x") + 480, 0, 240, 58).attr({fill: "#330000", stroke: "#330000", opacity: .5});
  transTitleRect.glow({width: 20, opacity: .1});
  
  var transTitleText = paper.text(divider.attr("x") + 600, 30, "Transactions").attr({fill: "#fff", opacity: 1});
  transTitleText.attr("font-size", "35");
  transTitleText.attr("font-family", "Lucida Grande");
  
  //and finally, the big border
  bigBorder = paper.rect(0, 0, 3000, 475).attr({opacity: .4});
  bigBorder.glow({width: 25, opacity: .1});


  window.transactions = [];
  $.getJSON('/transactions', function(data){
    transactions = data;
    $.each(transactions, function(_, transaction) {
       drawTransaction(transaction, {});
     });
   });

</script>    

<p><%= link_to 'New Category', new_category_path %></p>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cat name:</b>
  <%= @category.cat_name %>
</p>

<p>
  <b>Starting balance:</b>
  <%= @category.starting_balance %>
</p>

<p>
  <b>Current balance:</b>
  <%= @category.current_balance %>
</p>

<p>
  <b>Pocket balance:</b>
  <%= @category.pocket_balance %>
</p>

<p>
  <b>Change balance:</b>
  <%= @category.change_balance %>
</p>

<p>
  <b>Graph position number:</b>
  <%= @category.graph_position_number %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pocketchange</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :trans_amount %><br />
    <%= f.number_field :trans_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Trans amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.description %></td>
    <td><%= transaction.trans_amount %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>Trans amount:</b>
  <%= @transaction.trans_amount %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>